spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  properties:
    mail:
      smtp:
        starttls:
          enable: ${MAIL_TLS:false}

notification:
  service:
    base-url: ${NOTIFICATION_SERVICE_BASEURL}